package hud

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// docPath is the design doc that §7.3 pastes generated renders into.
var docPath = filepath.Join("..", "..", "docs", "design.md")

// embedded lists the golden renders that appear verbatim in docs/design.md §7.3.
var embedded = []string{
	"wide-healthy", "compact", "narrow", "degraded", "zero-vs-absent",
	"stale-scan-47s", "filter-sort", "empty-watching", "empty-unreadable",
	"help", "v1-capabilities", "column-hidden", "ascii",
}

// notEmbedded lists goldens deliberately kept out of the design doc, with the
// reason. "readme" is here because it belongs to README.md instead, and has its
// own gate below.
var notEmbedded = map[string]string{
	"floor-width":    "quoted inline in §7.2 as a one-line literal",
	"floor-height":   "quoted inline in §7.2 as a one-line literal",
	"stale-scan-90s": "identical layout to stale-scan-47s; only the notice styling differs",
	"quota-absent":   "described in §7.7; its layout is covered by wide-healthy",
	"readme":         "pasted into README.md; see TestReadmeHeroFrameMatchesItsGolden",
}

// The README's hero frame is the project's most public claim about what the HUD
// shows, and it makes a specific one: two absent cells and an estimate marker
// that are absent and estimated for real reasons. It is generated, so drift
// here is a fixable build failure rather than a screenshot that quietly ages.
func TestReadmeHeroFrameMatchesItsGolden(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "..", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	golden, err := os.ReadFile(filepath.Join("testdata", "golden", "readme.txt"))
	if err != nil {
		t.Fatal(err)
	}
	doc := strings.ReplaceAll(string(raw), "\r\n", "\n")
	want := strings.TrimRight(strings.ReplaceAll(string(golden), "\r\n", "\n"), "\n")
	if !strings.Contains(doc, want) {
		t.Errorf("README.md's HUD frame is stale.\n"+
			"Re-paste it from internal/hud/testdata/golden/readme.txt.\n--- expected ---\n%s", want)
	}
}

// The design doc is a contract, and a contract that drifts from the code is
// worse than no contract. §7.3 says the renders are generated by the build, so
// this asserts it rather than trusting it: if a render changes and the doc is
// not re-spliced, the build fails here.
func TestDesignDocRendersMatchTheGoldens(t *testing.T) {
	raw, err := os.ReadFile(docPath)
	if err != nil {
		t.Fatalf("%v — the HUD section is part of the deliverable", err)
	}
	doc := strings.ReplaceAll(string(raw), "\r\n", "\n")

	for _, name := range embedded {
		golden, err := os.ReadFile(filepath.Join("testdata", "golden", name+".txt"))
		if err != nil {
			t.Errorf("%s: %v", name, err)
			continue
		}
		want := strings.TrimRight(strings.ReplaceAll(string(golden), "\r\n", "\n"), "\n")
		if !strings.Contains(doc, want) {
			t.Errorf("docs/design.md no longer contains the %q render.\n"+
				"Re-splice §7.3 from internal/hud/testdata/golden/%s.txt.\n--- expected ---\n%s",
				name, name, want)
		}
	}
}

// Every golden must be either embedded in the doc or explicitly exempted, so a
// new render cannot be added and quietly left undocumented.
func TestEveryGoldenIsClassified(t *testing.T) {
	files, err := filepath.Glob(filepath.Join("testdata", "golden", "*.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if len(files) == 0 {
		t.Fatal("no goldens found; run: go test ./internal/hud -update")
	}

	known := map[string]bool{}
	for _, n := range embedded {
		known[n] = true
	}
	for n := range notEmbedded {
		known[n] = true
	}

	var orphans []string
	for _, f := range files {
		name := strings.TrimSuffix(filepath.Base(f), ".txt")
		if !known[name] {
			orphans = append(orphans, name)
		}
	}
	sort.Strings(orphans)
	if len(orphans) > 0 {
		t.Errorf("goldens neither embedded in docs/design.md nor exempted: %v\n"+
			"Add each to `embedded` (and paste it into §7.3) or to `notEmbedded` with a reason.",
			orphans)
	}
}

// The §7.2 grid table states a SESSION width per tier. Those numbers are what a
// reader measures the mockups against, so they are pinned here rather than
// recomputed by hand every time a column moves.
func TestDocumentedGridWidths(t *testing.T) {
	cases := []struct {
		width   int
		tier    Tier
		session int
	}{
		{120, TierWide, 59},
		{100, TierWide, 39},
		{99, TierCompact, 51},
		{80, TierCompact, 32},
		{79, TierNarrow, 41},
		{72, TierNarrow, 34},
		{60, TierNarrow, 22},
		{59, TierFloor, 0},
	}
	for _, c := range cases {
		got := resolveLayout(c.width, true, true)
		if got.Tier != c.tier {
			t.Errorf("width %d: tier %v, want %v", c.width, got.Tier, c.tier)
		}
		if got.Session != c.session {
			t.Errorf("width %d: SESSION is %d columns, doc §7.2 says %d", c.width, got.Session, c.session)
		}
	}
}
