# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Telltale < Formula
  desc "Dispatch room for several coding-agent CLIs, with an honest gauge underneath"
  homepage "https://github.com/sanlee-ys/telltale"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sanlee-ys/telltale/releases/download/v0.3.0/telltale_0.3.0_darwin_amd64.tar.gz"
      sha256 "f9771830a4f4a1355edf26e2a1b542bf8cf90d0bd4ec054794259d714f33707e"

      define_method(:install) do
        bin.install "telltale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sanlee-ys/telltale/releases/download/v0.3.0/telltale_0.3.0_darwin_arm64.tar.gz"
      sha256 "f2b4c74cfea4fdd29370516a1850d0be57ed2a915c8b7a7046bcc77b1dafc0d7"

      define_method(:install) do
        bin.install "telltale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanlee-ys/telltale/releases/download/v0.3.0/telltale_0.3.0_linux_amd64.tar.gz"
      sha256 "158051a2dae6ed9a7fb2bbf1694fbd659d845b78a963e340a71cb0258029f693"
      define_method(:install) do
        bin.install "telltale"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/telltale version")
  end
end
